# Generated by Django 2.1.2 on 2018-10-22 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20181018_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepreference',
            name='an',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursepreference',
            name='semaine',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(53)]),
        ),
        migrations.AlterField(
            model_name='roompreference',
            name='an',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roompreference',
            name='semaine',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(53)]),
        ),
    ]
