# Generated by Django 2.1.2 on 2018-12-19 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_grouptype_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['abbrev']},
        ),
    ]
