# Generated by Django 2.1.4 on 2018-12-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20181113_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['abbrev']},
        ),
    ]
