# Generated by Django 2.1.3 on 2018-11-16 15:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


def move_slot_start_time(apps, schema_editor):
    ScheduledCourse = apps.get_model('base', 'ScheduledCourse')
    for sc in ScheduledCourse.objects.all():
        time = sc.creneau.heure
        sc.start_time = time.hours * 60 + time.minutes
        sc.save()

def create_ct_constraints(apps, schema_editor):
    CourseType =  apps.get_model('base', 'CourseType')
    CourseStartTimeConstraint =  apps.get_model('base', 'CourseStartTimeConstraint')

    allowed = []
    morning = 8*60
    afternoon = 14*60 + 15
    allowed += [morning+90*i for i in range(3)]
    allowed += [afternoon+90*i for i in range(3)]
    
    for ct in CourseType.objects.all():
        ct_constraint = CourseStartTimeConstraint(course_type=ct,
                                                  allowed_start_times=allowed)
        ct_constraint.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20190120_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStartTimeConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_start_times', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, size=None)),
            ],
        ),
        migrations.AddField(
            model_name='coursetype',
            name='duration',
            field=models.PositiveSmallIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='scheduledcourse',
            name='start_time',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursestarttimeconstraint',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.CourseType'),
        ),
        migrations.RunPython(move_slot_start_time),
        migrations.RunPython(create_ct_constraints),
    ]
