# Generated by Django 2.1.3 on 2018-11-16 15:42

from django.db import migrations, models
import django.db.models.deletion

def move_slot_start_day(apps, schema_editor):
    ScheduledCourse = apps.get_model('base', 'ScheduledCourse')
    for sc in ScheduledCourse.objects.all():
        sc.day = sc.creneau.jour
        sc.save()

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20181116_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledcourse',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Day'),
        ),
        migrations.RunPython(move_slot_start_day),
    ]
