# Generated by Django 2.1.3 on 2018-11-16 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_scheduledcourse_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledcourse',
            name='creneau',
        ),
        migrations.AlterField(
            model_name='scheduledcourse',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Day'),
        ),
        migrations.AlterField(
            model_name='scheduledcourse',
            name='start_time',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
