# Generated by Django 2.1.7 on 2019-03-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20190120_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
