# Generated by Django 2.1.3 on 2018-11-17 21:38

from django.db import migrations, models

def move_slot_start_day_string(apps, schema_editor):
    ScheduledCourse = apps.get_model('base', 'ScheduledCourse')
    for sc in ScheduledCourse.objects.all():
        sc.tday = sc.day.day
        sc.save()

def move_coursemodification_slot(apps, schema_editor):
    CourseModification = apps.get_model('base', 'CourseModification')
    for cm in CourseModification.objects.all():
        cm.day_old = cm.creneau_old.jour.day
        t = cm.creneau_old.heure
        cm.start_time_old = t.hours*60 + t.minutes
        cm.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20181116_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodification',
            name='day_old',
            field=models.CharField(choices=[('m', 'monday'), ('tu', 'tuesday'), ('w', 'wednesday'), ('th', 'thursday'), ('f', 'friday'), ('sa', 'saturday'), ('su', 'sunday')], default='m', max_length=2),
        ),
        migrations.AddField(
            model_name='coursemodification',
            name='start_time_old',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduledcourse',
            name='tday',
            field=models.CharField(choices=[('m', 'monday'), ('tu', 'tuesday'), ('w', 'wednesday'), ('th', 'thursday'), ('f', 'friday'), ('sa', 'saturday'), ('su', 'sunday')], default='m', max_length=2),
        ),
        migrations.RunPython(move_slot_start_day_string),
        migrations.RunPython(move_coursemodification_slot),
    ]
