# Generated by Django 2.1.7 on 2019-03-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_module_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
