# Generated by Django 2.1.3 on 2018-11-17 21:57

from django.db import migrations, models

def move_slot_start_day_string(apps, schema_editor):
    ScheduledCourse = apps.get_model('base', 'ScheduledCourse')
    for sc in ScheduledCourse.objects.all():
        sc.tday = sc.day.day
        sc.save()

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20181117_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledcourse',
            name='tday',
            field=models.CharField(choices=[('m', 'monday'), ('tu', 'tuesday'), ('w', 'wednesday'), ('th', 'thursday'), ('f', 'friday'), ('sa', 'saturday'), ('su', 'sunday')], default='m', max_length=2),
        ),
        migrations.RunPython(move_slot_start_day_string),
    ]
