# Generated by Django 2.1.3 on 2018-11-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_scheduledcourse_tday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledcourse',
            name='day',
        ),
    ]
