# Generated by Django 2.1.3 on 2018-11-17 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_scheduledcourse_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledcourse',
            old_name='tday',
            new_name='day',
        ),
    ]
