# Generated by Django 2.1.3 on 2018-11-18 09:56

from django.db import migrations, models
import django.db.models.deletion

def create_time_general_settings(apps, schema_editor):
    TimeGeneralSettings = apps.get_model('base', 'TimeGeneralSettings')
    Department = apps.get_model('base', 'Department')

    for department in Department.objects.all():
        TimeGeneralSettings.objects.create(
                            department=department,
                            day_start_time=8*60,
                            day_finish_time=18*60+45,
                            lunch_break_start_time=12*60+30,
                            lunch_break_finish_time=14*60)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20181117_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeGeneralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_start_time', models.PositiveSmallIntegerField()),
                ('day_finish_time', models.PositiveSmallIntegerField()),
                ('lunch_break_start_time', models.PositiveSmallIntegerField()),
                ('lunch_break_finish_time', models.PositiveSmallIntegerField()),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Department')),
            ],
        ),
        migrations.RunPython(create_time_general_settings),
    ]
