# Generated by Django 2.1.3 on 2018-11-18 14:03

import django.contrib.postgres.fields
from django.db import migrations, models

def add_days_general_settings(apps, schema_editor):
    TimeGeneralSettings = apps.get_model('base', 'TimeGeneralSettings')
    Day = apps.get_model('base', 'Day')
    qs = TimeGeneralSettings.objects.all()
    if qs.exists():
        ts = TimeGeneralSettings.objects.all().first()
        ts.days = ['m', 'tu', 'w', 'th', 'f']
        ts.save()

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_timegeneralsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='timegeneralsettings',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('m', 'monday'), ('tu', 'tuesday'), ('w', 'wednesday'), ('th', 'thursday'), ('f', 'friday'), ('sa', 'saturday'), ('su', 'sunday')], max_length=2), blank=True, default=list, size=None),
        ),
        migrations.RunPython(add_days_general_settings),
    ]
