# Generated by Django 2.1.3 on 2018-11-23 13:48

from django.db import migrations, models
import django.db.models.deletion

def create_slots(apps, schema_editor):
    Slot = apps.get_model('base', 'Slot')
    Step = apps.get_model('base', 'Step')
    CourseSlot = apps.get_model('base', 'CourseSlot')
    for s in Slot.objects.all():
        tot_min = s.heure.hours*60+s.heure.minutes
        step = Step(day=s.jour.day,
                    start_time=tot_min,
                    duration=s.duration)
        step.save()
        cslot = CourseSlot(day=s.jour.day,
                           start_time=tot_min,
                           duration=s.duration)
        cslot.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20181118_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('m', 'monday'), ('tu', 'tuesday'), ('w', 'wednesday'), ('th', 'thursday'), ('f', 'friday'), ('sa', 'saturday'), ('su', 'sunday')], default='m', max_length=2)),
                ('start_time', models.PositiveSmallIntegerField()),
                ('duration', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseSlot',
            fields=[
                ('generalslot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.GeneralSlot')),
            ],
            bases=('base.generalslot',),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('generalslot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.GeneralSlot')),
            ],
            bases=('base.generalslot',),
        ),
        migrations.RunPython(create_slots),
    ]
