# Generated by Django 2.1.3 on 2018-11-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20181126_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepreference',
            name='creneau',
        ),
        migrations.RemoveField(
            model_name='roompreference',
            name='creneau',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='creneau',
        ),
        migrations.AlterField(
            model_name='coursepreference',
            name='duration',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='coursepreference',
            name='start_time',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='roompreference',
            name='duration',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='roompreference',
            name='start_time',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='duration',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='start_time',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
