# Generated by Django 2.0.7 on 2018-12-01 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20181126_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcost',
            name='work_copy',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupfreehalfday',
            name='work_copy',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorcost',
            name='work_copy',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursestarttimeconstraint',
            name='course_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.CourseType'),
        ),
    ]
