# Generated by Django 2.0.7 on 2018-12-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20181201_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcost',
            name='work_copy',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupfreehalfday',
            name='work_copy',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutorcost',
            name='work_copy',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
