# Generated by Django 2.1.3 on 2019-04-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20190117_1008'),
        ('displayweb', '0002_auto_20190424_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakingnews',
            name='department',
        ),
        migrations.RemoveField(
            model_name='groupdisplay',
            name='group',
        ),
        migrations.RemoveField(
            model_name='moduledisplay',
            name='module',
        ),
        migrations.RemoveField(
            model_name='trainingprogrammedisplay',
            name='training_programme',
        ),
        migrations.DeleteModel(
            name='BreakingNews',
        ),
        migrations.DeleteModel(
            name='GroupDisplay',
        ),
        migrations.DeleteModel(
            name='ModuleDisplay',
        ),
        migrations.DeleteModel(
            name='TrainingProgrammeDisplay',
        ),
    ]
