# Generated by Django 2.1.3 on 2019-11-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20190627_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependency',
            old_name='successifs',
            new_name='successive',
        ),
    ]
