# Generated by Django 2.1.4 on 2019-06-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_room_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='ppn',
            field=models.CharField(default='M', max_length=8),
        ),
    ]
