# Generated by Django 2.1.13 on 2019-10-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035b_successive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='jour',
            new_name='day',
        ),
    ]
