# Generated by Django 2.1.4 on 2019-10-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20191028_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='nom',
            field=models.CharField(max_length=10),
        ),
    ]
