# Generated by Django 2.1.13 on 2019-10-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20191024_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursepreference',
            old_name='valeur',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='groupcost',
            old_name='valeur',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='roompreference',
            old_name='valeur',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='tutorcost',
            old_name='valeur',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='userpreference',
            old_name='valeur',
            new_name='value',
        ),
    ]
