# Generated by Django 2.1.13 on 2019-10-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20191027_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodification',
            old_name='cours',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='dependency',
            old_name='cours1',
            new_name='course1',
        ),
        migrations.RenameField(
            model_name='dependency',
            old_name='cours2',
            new_name='course2',
        ),
        migrations.RenameField(
            model_name='planningmodification',
            old_name='cours',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='scheduledcourse',
            old_name='cours',
            new_name='course',
        ),
    ]
