# Generated by Django 2.1.13 on 2019-11-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20191106_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='an',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='coursemodification',
            old_name='an_old',
            new_name='old_year',
        ),
        migrations.RenameField(
            model_name='coursepreference',
            old_name='an',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='edtversion',
            old_name='an',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='groupcost',
            old_name='an',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='groupfreehalfday',
            old_name='an',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='planningmodification',
            old_name='an_old',
            new_name='old_year',
        ),
        migrations.RenameField(
            model_name='regen',
            old_name='an',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='roompreference',
            old_name='an',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='tutorcost',
            old_name='an',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='userpreference',
            old_name='an',
            new_name='year',
        ),
        migrations.AlterUniqueTogether(
            name='edtversion',
            unique_together={('department', 'week', 'year')},
        ),
    ]
