# Generated by Django 2.1.13 on 2019-10-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20191027_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledcourse',
            old_name='copie_travail',
            new_name='work_copy',
        ),
    ]
