# Generated by Django 2.1.13 on 2019-10-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20191027_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='groupe',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='groupcost',
            old_name='groupe',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='groupfreehalfday',
            old_name='groupe',
            new_name='group',
        ),
    ]
