# Generated by Django 2.1.3 on 2020-02-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_auto_20191127_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
