# Generated by Django 2.1.11 on 2020-02-28 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20200227_0819'),
        ('base', '0041_module_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsort',
            name='tutor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abcd', to='people.Tutor'),
        ),
    ]
