# Generated by Django 2.1.11 on 2020-02-27 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_module_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='train_prog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module', to='base.TrainingProgramme'),
        ),
        migrations.AlterField(
            model_name='trainingprogramme',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train_pro', to='base.Department'),
        ),
    ]
