# Generated by Django 2.1.3 on 2020-03-02 17:49

from django.db import migrations


def planif2course_modification(apps, schema_editor):
    CourseModification = apps.get_model('base', 'CourseModification')
    PlanningModification = apps.get_model('base', 'PlanningModification')
    for pm in PlanningModification.objects.all():
        cm = CourseModification(course=pm.course,
                                old_week=pm.old_week,
                                old_year=pm.old_year,
                                tutor_old=pm.tutor_old,
                                version_old=0,
                                initiator=pm.initiator)
        cm.save()
        CourseModification.objects.filter(id=cm.id).update(
            updated_at=pm.updated_at)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_auto_20200302_1718'),
    ]

    operations = [
        migrations.RunPython(planif2course_modification),
    ]
