# Generated by Django 2.1.3 on 2020-03-02 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_auto_20200302_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planningmodification',
            name='course',
        ),
        migrations.RemoveField(
            model_name='planningmodification',
            name='initiator',
        ),
        migrations.RemoveField(
            model_name='planningmodification',
            name='tutor_old',
        ),
        migrations.AlterField(
            model_name='coursemodification',
            name='tutor_old',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impacted_by_course_modif', to='people.Tutor'),
        ),
        migrations.DeleteModel(
            name='PlanningModification',
        ),
    ]
