# Generated by Django 2.1.3 on 2020-03-03 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_auto_20200302_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodification',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
