# Generated by Django 2.1.3 on 2020-03-04 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20200302_1718'),
        ('base', '0045_auto_20200303_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsort',
            name='tutor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abcd', to='people.Tutor'),
        ),
    ]
