# Generated by Django 2.1.3 on 2020-03-09 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_roomsort_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomgroup',
            name='basic',
            field=models.BooleanField(default=False, verbose_name='Basic room?'),
        ),
        migrations.AddField(
            model_name='roomgroup',
            name='departments',
            field=models.ManyToManyField(to='base.Department'),
        ),
        migrations.AddField(
            model_name='roomgroup',
            name='subroom_of',
            field=models.ManyToManyField(blank=True, related_name='subroomgroups', to='base.RoomGroup'),
        ),
        migrations.AlterField(
            model_name='roompreference',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.RoomGroup'),
        ),
    ]
