# Generated by Django 2.1.15 on 2020-03-10 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_module_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomgroup',
            name='basic',
            field=models.BooleanField(default=False, verbose_name='Basic room?'),
        ),
        migrations.AddField(
            model_name='roomgroup',
            name='departments',
            field=models.ManyToManyField(to='base.Department'),
        ),
        migrations.AddField(
            model_name='roomgroup',
            name='subroom_of',
            field=models.ManyToManyField(blank=True, related_name='subroomgroups', to='base.RoomGroup'),
        ),
        migrations.AddField(
            model_name='roompreference',
            name='roomgroup',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.RoomGroup'),
        ),
        migrations.AlterField(
            model_name='roompreference',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Room'),
        ),
    ]
