# Generated by Django 2.1.15 on 2020-03-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_roomsort_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
