# Generated by Django 2.1.15 on 2020-03-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_auto_20200309_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='room',
            name='subroom_of',
        ),
        migrations.RemoveField(
            model_name='roompreference',
            name='room',
        ),
        migrations.AlterField(
            model_name='roomgroup',
            name='subroom_of',
            field=models.ManyToManyField(blank=True, related_name='subrooms', to='base.RoomGroup'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
