# Generated by Django 2.1.15 on 2020-03-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TTapp', '0013_auto_20191028_2047'),
        ('base', '0049_auto_20200310_1233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomGroup',
            new_name='Room',
        ),
        migrations.RenameField(
            model_name='roompreference',
            old_name='roomgroup',
            new_name='room',
        ),
    ]
