# Generated by Django 2.1.3 on 2020-03-11 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_auto_20200310_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='basic',
        ),
    ]
