# Generated by Django 3.0.5 on 2020-04-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_remove_room_basic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
    ]
