# Generated by Django 2.1.3 on 2020-03-29 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_auto_20200320_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='abbrev',
            field=models.CharField(max_length=10, verbose_name='intitulé abbrégé'),
        ),
        migrations.AlterField(
            model_name='module',
            name='head',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Tutor', verbose_name='responsable'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='nom complet'),
        ),
        migrations.AlterField(
            model_name='module',
            name='ppn',
            field=models.CharField(default='M', max_length=8, verbose_name='référence PPN'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('train_prog', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='grouptype',
            unique_together={('department', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='trainingprogramme',
            unique_together={('department', 'abbrev')},
        ),
    ]
