# Generated by Django 2.1.15 on 2020-04-17 21:02

from django.db import migrations

def make_many_groups(apps, schema_editor):
    """
        Adds the Group object in Course.group to the
        many-to-many relationship in Course.groups
    """
    Course = apps.get_model('base', 'Course')

    for course in Course.objects.all():
        course.groups.add(course.group)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_auto_20200417_2101'),
    ]

    operations = [
        migrations.RunPython(make_many_groups),
    ]
