# Generated by Django 2.1.15 on 2020-03-31 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_auto_20200329_1719'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='grouptype',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='trainingprogramme',
            unique_together=set(),
        ),
    ]
