# Generated by Django 3.0.5 on 2020-07-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_auto_20200708_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledcourseadditional',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
