# Generated by Django 3.0.5 on 2020-07-20 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_scheduledcourseadditional_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAdditional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graded', models.BooleanField(default=False, verbose_name='noté ?')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional', to='base.Course')),
            ],
        ),
    ]
