# Generated by Django 3.0.5 on 2020-09-15 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_auto_20200915_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledcourseadditional',
            name='links',
        ),
        migrations.AddField(
            model_name='scheduledcourseadditional',
            name='link',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additionnal', to='base.EnrichedLink'),
        ),
        migrations.DeleteModel(
            name='VisioPreference',
        ),
    ]
