# Generated by Django 3.0.5 on 2020-09-18 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_auto_20200915_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseadditional',
            name='visio_preference_value',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
