# Generated by Django 3.0.5 on 2020-09-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_auto_20200918_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetype',
            name='graded',
            field=models.BooleanField(default=False, verbose_name='noté ?'),
        ),
    ]
