# Generated by Django 3.0.5 on 2020-09-21 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_coursetype_graded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledcourseadditional',
            name='link',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional', to='base.EnrichedLink'),
        ),
    ]
