# Generated by Django 3.0.5 on 2020-10-01 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_auto_20200921_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPreferredLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_links', to='base.Group')),
                ('links', models.ManyToManyField(related_name='group_set', to='base.EnrichedLink')),
            ],
        ),
    ]
