# Generated by Django 3.0.5 on 2021-03-07 13:41

from django.db import migrations, models
from datetime import date

def move_strange_date_to_date(apps, schema_editor):
    Regen = apps.get_model('base', 'Regen')
    for r in Regen.objects.all():
        if r.fyear > 2000:
            r.fdate = date(r.fyear, r.fmonth, r.fday)
        if r.syear > 2000:
            r.sdate = date(r.syear, r.smonth, r.sday)
        r.save()

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_grouppreferredlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='regen',
            name='fdate',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='regen',
            name='sdate',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.RunPython(move_strange_date_to_date),
        migrations.RemoveField(
            model_name='regen',
            name='fday',
        ),
        migrations.RemoveField(
            model_name='regen',
            name='fmonth',
        ),
        migrations.RemoveField(
            model_name='regen',
            name='fyear',
        ),
        migrations.RemoveField(
            model_name='regen',
            name='sday',
        ),
        migrations.RemoveField(
            model_name='regen',
            name='smonth',
        ),
        migrations.RemoveField(
            model_name='regen',
            name='syear',
        ),
    ]
