# Generated by Django 3.0.5 on 2021-03-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_auto_20210307_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='suspens',
            field=models.BooleanField(default=False, verbose_name='Suspens?'),
        ),
        migrations.AlterField(
            model_name='courseadditional',
            name='graded',
            field=models.BooleanField(default=False, verbose_name='Graded?'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='graded',
            field=models.BooleanField(default=False, verbose_name='graded?'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='ND',
            field=models.BooleanField(default=False, verbose_name='On different days'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='successive',
            field=models.BooleanField(default=False, verbose_name='Successives?'),
        ),
        migrations.AlterField(
            model_name='module',
            name='abbrev',
            field=models.CharField(max_length=10, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='regen',
            name='fdate',
            field=models.DateField(blank=True, null=True, verbose_name='Full generation date'),
        ),
        migrations.AlterField(
            model_name='regen',
            name='full',
            field=models.BooleanField(default=True, verbose_name='Full'),
        ),
        migrations.AlterField(
            model_name='regen',
            name='sdate',
            field=models.DateField(blank=True, null=True, verbose_name='Partial generation date'),
        ),
        migrations.AlterField(
            model_name='regen',
            name='stabilize',
            field=models.BooleanField(default=False, verbose_name='Stabilized'),
        ),
        migrations.AlterField(
            model_name='traininghalfday',
            name='apm',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], default=None, max_length=2, null=True, verbose_name='Half day'),
        ),
    ]
