# Generated by Django 3.0.13 on 2021-04-02 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_auto_20210314_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.GroupType'),
        ),
    ]
