# Generated by Django 3.0.5 on 2021-04-11 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0027_auto_20210314_1603'),
        ('base', '0068_auto_20210314_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='head',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Tutor', verbose_name='responsable'),
        ),
        migrations.CreateModel(
            name='DepartmentMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cosmo', models.BooleanField(default=False)),
                ('visio', models.BooleanField(default=False)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Department')),
            ],
        ),
    ]
