# Generated by Django 3.0.5 on 2021-04-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_auto_20210411_1504'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DepartmentMode',
            new_name='Mode',
        ),
    ]
