# Generated by Django 3.0.5 on 2021-04-11 15:48

from django.db import migrations, models

from base.timing import days_list

def create_dept_settings(apps, schema_editor):
    Department = apps.get_model('base', 'Department')
    TimeGeneralSettings = apps.get_model('base', 'TimeGeneralSettings')
    Mode = apps.get_model('base', 'Mode')

    print()
    for dept in Department.objects.all():
        if not TimeGeneralSettings.objects.filter(department=dept).exists():
            TimeGeneralSettings.objects.create(
                department=dept,
                day_start_time=6*60,
                day_finish_time=20*60,
                lunch_break_start_time=13*60,
                lunch_break_finish_time=13*60, 
                days=days_list 
            )
            print(f'Time general settings created for {dept.abbrev}.')

        if not Mode.objects.filter(department=dept).exists():
            Mode.objects.create(department=dept)
            print(f'Mode created for {dept.abbrev}.')


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_auto_20210411_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='visio',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(create_dept_settings),
    ]
