# Generated by Django 3.0.5 on 2021-04-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_auto_20210411_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodification',
            name='room_old_is_visio',
            field=models.BooleanField(default=False),
        ),
    ]
