# Generated by Django 3.0.5 on 2021-04-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_auto_20210407_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='abbrev',
            field=models.CharField(max_length=100, verbose_name='Abbreviation'),
        ),
    ]
