# Generated by Django 3.0.5 on 2021-05-11 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TTapp', '0042_auto_20210301_2100'),
        ('people', '0027_auto_20210314_1603'),
        ('displayweb', '0004_auto_20200515_1818'),
        ('base', '0072_auto_20210412_1553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='StructuralGroup',
        ),
        migrations.CreateModel(
            name='TransversalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.PositiveSmallIntegerField()),
                ('conflicting_groups', models.ManyToManyField(blank=True, to='base.StructuralGroup')),
                ('parallel_groups', models.ManyToManyField(blank=True, related_name='_transversalgroup_parallel_groups_+', to='base.TransversalGroup')),
                ('train_prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.TrainingProgramme')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.GroupType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
