# Generated by Django 3.0.5 on 2021-05-11 15:23

from django.db import migrations, models
import django.db.models.deletion
from base.models import Week


def move_week_year_to_week_tmp(apps, schema_editor):
    considered_classes = apps.get_model('base', '')
    for cc in considered_classes:
        for o in cc.objects.exclude(week=None):
            w=Week.objects.get(nb=o.week, year=o.year)
            o.week_tmp = w
            o.save()
    CM = apps.get_model('base', 'CourseModification')
    for o in CM.objects.exclude(old_week=None):
        w = Week.objects.get(nb=o.old_week, year=o.old_year)
        o.old_week_tmp = w
        o.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='week_tmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Week'),
        ),
        migrations.AddField(
            model_name='coursemodification',
            name='old_week_tmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Week'),
        ),
        migrations.AddField(
            model_name='coursepreference',
            name='week_tmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Week'),
        ),
        migrations.AddField(
            model_name='edtversion',
            name='week_tmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Week'),
        ),
        migrations.AddField(
            model_name='groupcost',
            name='week_tmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Week'),
        ),
        migrations.AddField(
            model_name='groupfreehalfday',
            name='week_tmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Week'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='week_tmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Week'),
        ),
        migrations.AddField(
            model_name='moduletutorrepartition',
            name='week_tmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Week'),
        ),
        migrations.AddField(
            model_name='regen',
            name='week_tmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Week'),
        ),
        migrations.AddField(
            model_name='roompreference',
            name='week_tmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Week'),
        ),
        migrations.AddField(
            model_name='traininghalfday',
            name='week_tmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Week'),
        ),
        migrations.AddField(
            model_name='tutorcost',
            name='week_tmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Week'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='week_tmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Week'),
        ),
        migrations.RunPython(move_week_year_to_week_tmp),
    ]
