# Generated by Django 3.1.7 on 2021-06-18 14:09

from django.db import migrations, models
import django.db.models.deletion

def create_and_add_generic_groups(apps, schema_editor):
    GenericGroup = apps.get_model('base', 'GenericGroup')
    StructuralGroup = apps.get_model('base', 'StructuralGroup')
    for g in StructuralGroup.objects.all():
        gg = GenericGroup.objects.create(name=g.name, size=g.size, train_prog=g.train_prog, type=g.type, id=g.id)
        g.generic = gg
        g.save()


def add_generic_groups_to_courses(apps, schema_editor):
    Course = apps.get_model('base', 'Course')
    for c in Course.objects.all():
        for g in c.groups.all():
            gg = g.generic
            c.generic_groups.add(gg)
            c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_auto_20210618_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.PositiveSmallIntegerField()),
                ('train_prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.trainingprogramme')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.grouptype')),
            ],
        ),
        migrations.AddField(
            model_name='structuralgroup',
            name='generic',
            field=models.OneToOneField(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                       to='base.genericgroup'),
            preserve_default=False,
        ),
        migrations.RunPython(create_and_add_generic_groups),
        migrations.AlterField(
            model_name='structuralgroup',
            name='generic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                       to='base.genericgroup'),
        ),
        migrations.AddField(
            model_name='course',
            name='generic_groups',
            field=models.ManyToManyField(blank=True, related_name='courses', to='base.GenericGroup'),
        ),
        migrations.RunPython(add_generic_groups_to_courses),
        migrations.CreateModel(
            name='TransversalGroup',
            fields=[
                ('generic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.genericgroup')),
                ('conflicting_groups', models.ManyToManyField(blank=True, to='base.StructuralGroup')),
                ('parallel_groups', models.ManyToManyField(blank=True, related_name='_transversalgroup_parallel_groups_+', to='base.TransversalGroup')),
            ],
            bases=('base.genericgroup',),
        ),
    ]
