# Generated by Django 3.0.5 on 2021-05-11 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_auto_20210511_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.RemoveField(
            model_name='coursemodification',
            name='old_year',
        ),
        migrations.RemoveField(
            model_name='coursepreference',
            name='year',
        ),
        migrations.RemoveField(
            model_name='groupcost',
            name='year',
        ),
        migrations.RemoveField(
            model_name='groupfreehalfday',
            name='year',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='year',
        ),
        migrations.RemoveField(
            model_name='moduletutorrepartition',
            name='year',
        ),
        migrations.RemoveField(
            model_name='regen',
            name='year',
        ),
        migrations.RemoveField(
            model_name='roompreference',
            name='year',
        ),
        migrations.RemoveField(
            model_name='traininghalfday',
            name='year',
        ),
        migrations.RemoveField(
            model_name='tutorcost',
            name='year',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='year',
        ),
        migrations.RemoveField(
            model_name='edtversion',
            name='year',
        ),
        migrations.RemoveField(
            model_name='course',
            name='week',
        ),
        migrations.RemoveField(
            model_name='coursemodification',
            name='old_week',
        ),
        migrations.RemoveField(
            model_name='coursepreference',
            name='week',
        ),
        migrations.RemoveField(
            model_name='groupcost',
            name='week',
        ),
        migrations.RemoveField(
            model_name='groupfreehalfday',
            name='week',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='week',
        ),
        migrations.RemoveField(
            model_name='moduletutorrepartition',
            name='week',
        ),
        migrations.RemoveField(
            model_name='regen',
            name='week',
        ),
        migrations.RemoveField(
            model_name='roompreference',
            name='week',
        ),
        migrations.RemoveField(
            model_name='traininghalfday',
            name='week',
        ),
        migrations.RemoveField(
            model_name='tutorcost',
            name='week',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='week',
        ),
        migrations.RemoveField(
            model_name='edtversion',
            name='week',
        ),
    ]
