# Generated by Django 3.1.7 on 2021-06-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_remove_course_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='generic_groups',
            new_name='groups',
        ),
    ]
