# Generated by Django 3.0.5 on 2021-05-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_auto_20210511_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='week_tmp',
            new_name='week',
        ),
        migrations.RenameField(
            model_name='coursemodification',
            old_name='old_week_tmp',
            new_name='old_week',
        ),
        migrations.RenameField(
            model_name='coursepreference',
            old_name='week_tmp',
            new_name='week',
        ),
        migrations.RenameField(
            model_name='edtversion',
            old_name='week_tmp',
            new_name='week',
        ),
        migrations.RenameField(
            model_name='groupcost',
            old_name='week_tmp',
            new_name='week',
        ),
        migrations.RenameField(
            model_name='groupfreehalfday',
            old_name='week_tmp',
            new_name='week',
        ),
        migrations.RenameField(
            model_name='holiday',
            old_name='week_tmp',
            new_name='week',
        ),
        migrations.RenameField(
            model_name='moduletutorrepartition',
            old_name='week_tmp',
            new_name='week',
        ),
        migrations.RenameField(
            model_name='regen',
            old_name='week_tmp',
            new_name='week',
        ),
        migrations.RenameField(
            model_name='roompreference',
            old_name='week_tmp',
            new_name='week',
        ),
        migrations.RenameField(
            model_name='traininghalfday',
            old_name='week_tmp',
            new_name='week',
        ),
        migrations.RenameField(
            model_name='tutorcost',
            old_name='week_tmp',
            new_name='week',
        ),
        migrations.RenameField(
            model_name='userpreference',
            old_name='week_tmp',
            new_name='week',
        ),
        migrations.AlterUniqueTogether(
            name='edtversion',
            unique_together={('department', 'week')},
        ),
    ]
