# Generated by Django 3.1.7 on 2021-06-18 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_auto_20210618_1420'),
        ('people', '0028_auto_20210618_1409')
    ]

    operations = [
        migrations.RemoveField(
            model_name='structuralgroup',
            name='id',
        ),
        migrations.RemoveField(
            model_name='structuralgroup',
            name='name',
        ),
        migrations.RemoveField(
            model_name='structuralgroup',
            name='size',
        ),
        migrations.RemoveField(
            model_name='structuralgroup',
            name='train_prog',
        ),
        migrations.RemoveField(
            model_name='structuralgroup',
            name='type',
        ),
        migrations.AlterField(
            model_name='structuralgroup',
            name='generic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.genericgroup'),
        ),
    ]
