# Generated by Django 3.1.7 on 2021-07-09 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_auto_20210511_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='nb',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(53)], verbose_name='Week number'),
        ),
        migrations.AlterUniqueTogether(
            name='edtversion',
            unique_together=set(),
        ),
    ]
