# Generated by Django 3.0.5 on 2021-06-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_auto_20210511_1707'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='edtversion',
            unique_together=set(),
        ),
    ]
