# Generated by Django 3.1.7 on 2021-07-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_auto_20210709_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mode',
            old_name='new_cosmo',
            new_name='cosmo',
        ),
        migrations.RemoveField(
            model_name='mode',
            name='ex_cosmo',
        ),
    ]
