# Generated by Django 3.0.14 on 2021-07-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_auto_20210629_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency',
            name='day_gap',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Minimal day gap between courses'),
        ),
    ]
