# Generated by Django 3.1.7 on 2021-07-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_auto_20210709_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='cosmo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Educative'), (1, 'Coop. (workplace)'), (2, 'Coop. (worker)')], default=0),
        ),
    ]
