# Generated by Django 3.1.7 on 2021-07-10 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_dependency_day_gap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='nb',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(53)], verbose_name='Week number'),
        ),
    ]
