# Generated by Django 3.0.14 on 2022-02-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_roomponderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomponderation',
            name='basic_rooms',
            field=models.ManyToManyField(to='base.Room'),
        ),
    ]
