# Generated by Django 3.0.14 on 2022-06-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0086_auto_20220616_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
