# Generated by Django 3.0.14 on 2022-10-03 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_courseadditional_over_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BooleanRoomAttribute',
            fields=[
                ('attribute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.RoomAttribute')),
            ],
            bases=('base.roomattribute',),
        ),
        migrations.CreateModel(
            name='NumericRoomAttribute',
            fields=[
                ('attribute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.RoomAttribute')),
            ],
            bases=('base.roomattribute',),
        ),
        migrations.CreateModel(
            name='NumericRoomAttributeValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Room')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.NumericRoomAttribute')),
            ],
        ),
        migrations.CreateModel(
            name='BooleanRoomAttributeValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Room')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.BooleanRoomAttribute')),
            ],
        ),
    ]
