# Generated by Django 3.0.14 on 2022-10-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0089_booleanroomattribute_booleanroomattributevalues_numericroomattribute_numericroomattributevalues_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BooleanRoomAttributeValues',
            new_name='BooleanRoomAttributeValue',
        ),
        migrations.RenameModel(
            old_name='NumericRoomAttributeValues',
            new_name='NumericRoomAttributeValue',
        ),
    ]
