# Generated by Django 3.0.14 on 2022-11-24 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0090_auto_20221003_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledcourse',
            old_name='no',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='no',
        ),
    ]
