# Generated by Django 3.0.14 on 2022-04-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupmodif',
            name='course_type_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
