from django.conf.urls import url, include
from .student import AddStudent
from .tutor import AddFullStaffTutor, AddSupplyStaffTutor, AddBIATOSTutor
from django.contrib.auth import views as auth_views

urlpatterns = [
#    url(r'^login', views.login, name="login"),
    url(r'^login/$',
        auth_views.login,
        {'template_name':'people/login.html'},
        name='login'),
    url(r'^logout/$',
        auth_views.logout,
        {'next_page': '/'},
        name='logout'),
    url(r'^password-reset/$',
        auth_views.password_reset,
        {'template_name':'people/password_reset_form.html',
         'email_template_name':'people/password_reset_email.html',
         'subject_template_name':'people/password_reset_subject.txt',
         'post_reset_redirect':'people:password_reset_done'},
        name='password_reset'),
    url(r'^pwd-reset-done/$',
        auth_views.password_reset_done,
        {'template_name':'people/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^password-change/$',
        auth_views.password_change,
        {'template_name':'people/password_change_form.html',
         'post_change_redirect':'people:password_change_done'},
        name='password_change'),
    url(r'^pwd-chg-done/$',
        auth_views.password_change_done,
        {'template_name':'people/password_change_done.html'},
        name='password_change_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'template_name':'people/password_reset_confirm.html'},
        name='password_reset_confirm'),
    url(r'^add-student/$',
        AddStudent.as_view(),
        name="add_student"),
    url(r'^add-fullstaff/$',
        AddFullStaffTutor.as_view(),
        name="add_fullstaff"),
    url(r'^add-supplystaff/$',
        AddSupplyStaffTutor.as_view(),
        name="add_supplystaff"),
    url(r'^add-biatos/$',
        AddBIATOSTutor.as_view(),
        name="add_bi"),
    ]
