# Generated by Django 2.1.2 on 2018-10-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20181018_1344'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullstaff',
            name='department',
        ),
        migrations.AddField(
            model_name='fullstaff',
            name='departments',
            field=models.ManyToManyField(blank=True, to='base.Department'),
        ),
    ]
