# Generated by Django 2.1.4 on 2019-01-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20181219_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplystaff',
            name='employer',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Employeur ?'),
        ),
        migrations.AlterField(
            model_name='supplystaff',
            name='field',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Domaine ?'),
        ),
        migrations.AlterField(
            model_name='supplystaff',
            name='position',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
