# Generated by Django 2.1.4 on 2019-06-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20190311_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='pref_slots_per_day',
        ),
        migrations.AddField(
            model_name='tutor',
            name='pref_hours_per_day',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='How many hours per day would you prefer ?'),
        ),
    ]
