# Generated by Django 2.1.9 on 2019-06-18 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_timegeneralsettings_default_preference_duration'),
        ('people', '0008_auto_20190611_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDepartmentSettings',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False)),
                ('department', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='base.Department')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
