# Generated by Django 2.1.9 on 2019-06-18 12:43

from django.db import migrations, models


def transfert_departments(apps, schema_editor):
    """
    Migrate department membership for Students and Tutor to User level
    """
    Tutor = apps.get_model('people', 'Tutor')
    Student = apps.get_model('people', 'Student')
    UserDepartmentSettings = apps.get_model(
        'people', 'UserDepartmentSettings')

    # Migrate tutor's departments
    for tutor in Tutor.objects.all():
        for department in tutor.departments.all():
            UserDepartmentSettings.objects.create(
                department=department, user=tutor)

    # Migrate student's departments
    for student in Student.objects.all():
        group = student.belong_to.first()
        if group and group.train_prog:
            UserDepartmentSettings.objects.create(
                department=group.train_prog.department, user=student)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_timegeneralsettings_default_preference_duration'),
        ('people', '0009_userdepartmentsettings'),
    ]

    operations = [
        migrations.RunPython(transfert_departments),
        migrations.RemoveField(
            model_name='tutor',
            name='departments',
        ),
        migrations.AddField(
            model_name='user',
            name='departments',
            field=models.ManyToManyField(
                through='people.UserDepartmentSettings', to='base.Department'),
        ),
    ]
