# Generated by Django 2.1.4 on 2019-09-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_auto_20190624_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='max_hours_per_day',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='How many hours per day can you suffer ?'),
        ),
    ]
