# Generated by Django 2.1.4 on 2019-09-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_tutor_max_hours_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='max_hours_per_day',
            field=models.PositiveSmallIntegerField(default=9, verbose_name='How many hours per day can you suffer ?'),
        ),
    ]
