# Generated by Django 2.1.3 on 2020-01-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20190926_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullstaff',
            name='department',
        ),
    ]
