# Generated by Django 2.1.3 on 2020-03-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_userdepartmentsettings_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'Tutor'},
        ),
    ]
