# Generated by Django 2.1.15 on 2020-03-26 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20200302_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_of_notified_weeks', models.PositiveSmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
