# Generated by Django 3.0.5 on 2020-10-01 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_grouppreferredlinks'),
        ('people', '0020_physicalpresence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferredlinks',
            name='links',
            field=models.ManyToManyField(related_name='ex_user_set', to='base.EnrichedLink'),
        ),
        migrations.CreateModel(
            name='UserPreferredLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.ManyToManyField(related_name='new_user_set', to='base.EnrichedLink')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='new_preferred_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
