# Generated by Django 3.0.5 on 2020-10-01 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_grouppreferredlinks'),
        ('people', '0021_auto_20201001_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferredlinks',
            name='links',
            field=models.ManyToManyField(related_name='user_set', to='base.EnrichedLink'),
        ),
        migrations.AlterField(
            model_name='userpreferredlinks',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PreferredLinks',
        ),
    ]
