# Generated by Django 3.0.13 on 2021-03-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0022_auto_20201001_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppreferences',
            name='eat_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='grouppreferences',
            name='hole_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='studentpreferences',
            name='eat_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='studentpreferences',
            name='hole_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.5, max_digits=3),
        ),
    ]
