# Generated by Django 3.0.13 on 2021-03-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_auto_20210304_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppreferences',
            name='eat_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.3, max_digits=3),
        ),
        migrations.AlterField(
            model_name='grouppreferences',
            name='hole_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.3, max_digits=3),
        ),
        migrations.AlterField(
            model_name='studentpreferences',
            name='eat_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.3, max_digits=3),
        ),
        migrations.AlterField(
            model_name='studentpreferences',
            name='hole_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.3, max_digits=3),
        ),
    ]
