# Generated by Django 3.0.13 on 2021-03-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0024_auto_20210304_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppreferences',
            name='free_half_day_choice_id',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='studentpreferences',
            name='free_half_day_choice_id',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
