# Generated by Django 3.0.13 on 2021-03-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0025_auto_20210305_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppreferences',
            name='free_half_day_choice_id',
        ),
        migrations.RemoveField(
            model_name='studentpreferences',
            name='free_half_day_choice_id',
        ),
    ]
