# Generated by Django 3.0.5 on 2021-03-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0026_auto_20210305_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppreferences',
            name='eat_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.5, max_digits=3),
        ),
        migrations.AlterField(
            model_name='grouppreferences',
            name='hole_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.5, max_digits=3),
        ),
        migrations.AlterField(
            model_name='studentpreferences',
            name='eat_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.5, max_digits=3),
        ),
        migrations.AlterField(
            model_name='studentpreferences',
            name='hole_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.5, max_digits=3),
        ),
    ]
