# Generated by Django 3.1.7 on 2021-06-18 14:09

from django.db import migrations, models


def add_generic_groups_to_students(apps, schema_editor):
    Student = apps.get_model('people', 'Student')
    for s in Student.objects.all():
        for g in s.belong_to.all():
            gg = g.generic
            s.generic_belong_to.add(gg)
            s.save()

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_auto_20210618_1409'),
        ('people', '0031_auto_20210709_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='generic_belong_to',
            field=models.ManyToManyField(blank=True, to='base.GenericGroup'),
        ),
        migrations.RunPython(add_generic_groups_to_students),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
