# Generated by Django 3.0.5 on 2021-05-11 15:23

from django.db import migrations, models
import django.db.models.deletion


def move_week_year_to_week_tmp(apps, schema_editor):
    CM = apps.get_model('people', 'PhysicalPresence')
    Week = apps.get_model('base', 'Week')
    for o in CM.objects.exclude(week=None):
        w = Week.objects.get(nb=o.week, year=o.year)
        o.week_tmp = w
        o.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_auto_20210511_1523'),
        ('people', '0027_auto_20210314_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalpresence',
            name='week_tmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Week'),
        ),
        migrations.RunPython(move_week_year_to_week_tmp),
    ]
