# Generated by Django 3.0.5 on 2021-05-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0028_physicalpresence_week_tmp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalpresence',
            name='week',
        ),
        migrations.RemoveField(
            model_name='physicalpresence',
            name='year',
        ),
    ]
