# Generated by Django 3.1.7 on 2021-06-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0028_auto_20210618_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='belong_to',
        ),
    ]
