# Generated by Django 3.0.14 on 2022-03-15 22:30

from django.db import migrations, models
import django.db.models.deletion

def create_tutor_preferences(apps, schema_editor):
    Tutor = apps.get_model('people', 'Tutor')
    TutorPreference = apps.get_model('people', 'TutorPreference')
    for t in Tutor.objects.all():
        TutorPreference.objects.create(tutor=t,
                                       pref_hours_per_day=t.pref_hours_per_day,
                                       max_hours_per_day=t.max_hours_per_day)


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0031_auto_20220214_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_hours_per_day', models.PositiveSmallIntegerField(default=4, verbose_name='How many hours per day would you prefer ?')),
                ('max_hours_per_day', models.PositiveSmallIntegerField(default=9, verbose_name='How many hours per day can you suffer ?')),
                ('min_hours_per_day', models.PositiveSmallIntegerField(default=0, verbose_name='Under how many hours would you prefer to avoid to have class?')),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='people.Tutor')),
            ],
        ),
        migrations.RunPython(create_tutor_preferences),
    ]
