# Generated by Django 3.0.14 on 2022-03-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0031_auto_20220214_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preffered_theme',
            field=models.CharField(default='WHITE', max_length=20),
        ),
    ]
