# Generated by Django 3.0.14 on 2022-03-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0033_auto_20220310_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppreferences',
            name='theme',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='studentpreferences',
            name='theme',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
