# Generated by Django 3.0.14 on 2022-03-28 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0033_auto_20220315_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemesPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='White', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='themes_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
