# Generated by Django 3.0.14 on 2022-08-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0034_themespreferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='belong_to',
            new_name='generic_groups',
        ),
    ]
