# Generated by Django 3.0.14 on 2022-11-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0035_auto_20220809_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationspreferences',
            name='notify_other_user_modifications',
            field=models.BooleanField(default=False),
        ),
    ]
