# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 09:55
from __future__ import unicode_literals

from django.db import migrations, models


def create_fake_user(apps, schema_editor):
    User = apps.get_model('django.contrib.auth.models.User')
    FakeUser = apps.get_model('FakeUser')
    for u in User.objects.all():
        fu = FakeUser(
            username = u.username,
            first_name = u.first_name,
            last_name = u.last_name,
            email = u.email,
            password = u.password,
            is_staff = u.is_staff,
            is_active = u.is_active,
            is_superuser = u.is_superuser
        )
        fu.save()


def create_tutor_names(apps, schema_editor):

    Module = apps.get_model('Module')
    for m in Module.objects.all():
        m.head_name = m.responsable.username
        m.save()

    CoursModification = apps.get_model('CoursModification')
    for cm in CoursModification.objects.all():
        cm.initiator_name = cm.user.username
        cm.save()

    PlanifModification = apps.get_model('PlanifModification')
    for pm in PlanifModification.objects.all():
        pm.initiator_name = pm.user.username
        pm.tutor_name_old = pm.prof_old
        pm.save()



class Migration(migrations.Migration):

    dependencies = [
        ('modif', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('is_superuser', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='head_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.RunPython(create_fake_user),
        migrations.RunPython(create_tutor_names),
    ]
