# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def create_training_programmes(apps, schema_editor):
    Groupe = apps.get_model('modif', 'Groupe')
    TrainingProgramme = apps.get_model('modif', 'TrainingProgramme')
    tp = {}
    tp['1'] = TrainingProgramme(name = '1A', abbrev = '1A')
    tp['2'] = TrainingProgramme(name = '2A', abbrev = '2A')
    tp['3'] = TrainingProgramme(name = 'LP APSIO', abbrev = '3A')
    tp['1'].save()
    tp['2'].save()
    tp['3'].save()

    for g in Groupe.objects.all():
        g.train_prog = tp[g.nom[0]]
        g.nom = g.nom[2:]
        g.save()


class Migration(migrations.Migration):

    dependencies = [
        ('modif', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modif.Module')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgramme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbrev', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgrammeDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveSmallIntegerField()),
                ('training_programme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modif.TrainingProgramme')),
            ],
        ),
        migrations.AddField(
            model_name='groupe',
            name='train_prog',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.TrainingProgramme'),
        ),
        migrations.RunPython(create_training_programmes),

    ]
