# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modif', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutorcost',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Tutor'),
        ),
        migrations.AddField(
            model_name='trainingprogrammedisplay',
            name='training_programme',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='modif.TrainingProgramme'),
        ),
        migrations.AddField(
            model_name='traininghalfday',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modif.Day'),
        ),
        migrations.AddField(
            model_name='traininghalfday',
            name='train_prog',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.TrainingProgramme'),
        ),
        migrations.AddField(
            model_name='slot',
            name='heure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modif.Time'),
        ),
        migrations.AddField(
            model_name='slot',
            name='jour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modif.Day'),
        ),
        migrations.AddField(
            model_name='scheduledcourse',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modif.Course'),
        ),
        migrations.AddField(
            model_name='scheduledcourse',
            name='creneau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modif.Slot'),
        ),
        migrations.AddField(
            model_name='scheduledcourse',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.RoomGroup'),
        ),
        migrations.AddField(
            model_name='roomsort',
            name='for_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='modif.RoomType'),
        ),
        migrations.AddField(
            model_name='roomsort',
            name='prefer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='modif.RoomGroup'),
        ),
        migrations.AddField(
            model_name='roomsort',
            name='unprefer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='modif.RoomGroup'),
        ),
        migrations.AddField(
            model_name='roompreference',
            name='creneau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modif.Slot'),
        ),
        migrations.AddField(
            model_name='roompreference',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modif.Room'),
        ),
        migrations.AddField(
            model_name='roomgroup',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='members', to='modif.RoomType'),
        ),
        migrations.AddField(
            model_name='room',
            name='subroom_of',
            field=models.ManyToManyField(blank=True, related_name='subrooms', to='modif.RoomGroup'),
        ),
        migrations.AddField(
            model_name='planningmodification',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modif.Course'),
        ),
        migrations.AddField(
            model_name='planningmodification',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operated_planif_modif', to='people.Tutor'),
        ),
        migrations.AddField(
            model_name='planningmodification',
            name='tutor_old',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impacted_by_planif_modif', to='people.Tutor'),
        ),
        migrations.AddField(
            model_name='moduledisplay',
            name='module',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='modif.Module'),
        ),
        migrations.AddField(
            model_name='module',
            name='head',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Tutor'),
        ),
        migrations.AddField(
            model_name='module',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modif.Period'),
        ),
        migrations.AddField(
            model_name='module',
            name='train_prog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modif.TrainingProgramme'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modif.Day'),
        ),
        migrations.AddField(
            model_name='groupfreehalfday',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modif.Group'),
        ),
        migrations.AddField(
            model_name='groupdisplay',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='modif.Group'),
        ),
        migrations.AddField(
            model_name='groupcost',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modif.Group'),
        ),
        migrations.AddField(
            model_name='group',
            name='parent_groups',
            field=models.ManyToManyField(blank=True, related_name='children_groups', to='modif.Group'),
        ),
        migrations.AddField(
            model_name='group',
            name='train_prog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modif.TrainingProgramme'),
        ),
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modif.GroupType'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='cours1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours1', to='modif.Course'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='cours2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours2', to='modif.Course'),
        ),
        migrations.AddField(
            model_name='coursepreference',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modif.CourseType'),
        ),
        migrations.AddField(
            model_name='coursepreference',
            name='creneau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modif.Slot'),
        ),
        migrations.AddField(
            model_name='coursepreference',
            name='train_prog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modif.TrainingProgramme'),
        ),
        migrations.AddField(
            model_name='coursemodification',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modif.Course'),
        ),
        migrations.AddField(
            model_name='coursemodification',
            name='creneau_old',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.Slot'),
        ),
        migrations.AddField(
            model_name='coursemodification',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Tutor'),
        ),
        migrations.AddField(
            model_name='coursemodification',
            name='room_old',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.RoomGroup'),
        ),
        migrations.AddField(
            model_name='course',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modif.Group'),
        ),
        migrations.AddField(
            model_name='course',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module', to='modif.Module'),
        ),
        migrations.AddField(
            model_name='course',
            name='modulesupp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulesupp', to='modif.Module'),
        ),
        migrations.AddField(
            model_name='course',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.RoomType'),
        ),
        migrations.AddField(
            model_name='course',
            name='supp_tutor',
            field=models.ManyToManyField(blank=True, related_name='courses_as_supp', to='people.Tutor'),
        ),
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taught_courses', to='people.Tutor'),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modif.CourseType'),
        ),
    ]
