# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 20:48
from __future__ import unicode_literals

from django.db import migrations, models


def create_mtom(apps, schema_editor):
    Groupe = apps.get_model('modif', 'Groupe')
    for gp in Groupe.objects.all():
        if gp.surgroupe is not None:
            gp.parent_groups.add(gp.surgroupe)
            gp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('modif', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name = 'groupe',
            old_name = 'taille',
            new_name = 'size',
        ),
        migrations.AddField(
            model_name = 'groupe',
            name = 'parent_groups',
            field = models.ManyToManyField(blank = True,
                                           related_name = '_groupe_parent_groups_+',
                                           to = 'modif.Groupe'),
        ),
        migrations.RunPython(create_mtom),
        migrations.RemoveField(
            model_name = 'groupe',
            name = 'surgroupe',
        ),

    ]
