# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modif', '0002_auto_20180706_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogrammedisplay',
            name='short_name',
            field=models.CharField(default='red', max_length=20),
        ),
    ]
