# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modif', '0002_module_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='train_prog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modif.TrainingProgramme'),
        ),
    ]
