# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def move_training_programmes(apps, schema_editor):
    TrainingProgramme = apps.get_model('modif', 'TrainingProgramme')
    Module = apps.get_model('modif', 'Module')
    DispoCours = apps.get_model('modif', 'DispoCours')
    DemiJourFeriePromo = apps.get_model('modif', 'DemiJourFeriePromo')

    tp = {}
    tp['1'] = TrainingProgramme.objects.get(abbrev = '1A')
    tp['2'] = TrainingProgramme.objects.get(abbrev = '2A')
    tp['3'] = TrainingProgramme.objects.get(abbrev = '3A')

    for obj in Module.objects.all():
        obj.train_prog = tp[str(obj.promo)]
        obj.save()
    for obj in DispoCours.objects.all():
        obj.train_prog = tp[str(obj.promo)]
        obj.save()
    for obj in DemiJourFeriePromo.objects.all():
        obj.train_prog = tp[str(obj.promo)]
        obj.save()



class Migration(migrations.Migration):

    dependencies = [
        ('modif', '0003_nonnull_tp'),
    ]

    operations = [
        migrations.AddField(
            model_name='demijourferiepromo',
            name='train_prog',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.TrainingProgramme'),
        ),
        migrations.AddField(
            model_name='dispocours',
            name='train_prog',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.TrainingProgramme'),
        ),
        migrations.AddField(
            model_name='module',
            name='train_prog',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.TrainingProgramme'),
        ),
        migrations.RunPython(move_training_programmes),
    ]
