# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modif', '0003_welcome_tutor_b'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biatostmp',
            name='tutor_name',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='supp_tutor_name',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='tutor_name',
        ),
        migrations.RemoveField(
            model_name='coursmodification',
            name='initiator_name',
        ),
        migrations.RemoveField(
            model_name='coutprof',
            name='tutor_name',
        ),
        migrations.RemoveField(
            model_name='disponibilite',
            name='tutor_name',
        ),
        migrations.RemoveField(
            model_name='fullstafftmp',
            name='tutor_name',
        ),
        migrations.RemoveField(
            model_name='module',
            name='head_name',
        ),
        migrations.RemoveField(
            model_name='planifmodification',
            name='initiator_name',
        ),
        migrations.RemoveField(
            model_name='planifmodification',
            name='tutor_name_old',
        ),
        migrations.RemoveField(
            model_name='vacatairetmp',
            name='tutor_name',
        ),
        migrations.AlterField(
            model_name='coursmodification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='planifmodification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
