# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modif', '0005_auto_20180604_1125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BIATOSTmp',
            new_name='BIATOS',
        ),
        migrations.RenameModel(
            old_name='FullStaffTmp',
            new_name='FullStaff',
        ),
        migrations.RenameModel(
            old_name='VacataireTmp',
            new_name='SupplyStaff',
        ),
    ]
