# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modif', '0005_remove_promo_remove_tp_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_height', models.PositiveIntegerField()),
                ('button_txt', models.CharField(max_length=20)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='modif.Groupe')),
            ],
        ),
        migrations.AlterField(
            model_name='moduledisplay',
            name='module',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='modif.Module'),
        ),
        migrations.AlterField(
            model_name='trainingprogrammedisplay',
            name='training_programme',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='modif.TrainingProgramme'),
        ),
    ]
