# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 18:07
from __future__ import unicode_literals

from django.db import migrations, models


def move_LP_n_displays(apps, schema_editor):
    TrainingProgramme = apps.get_model('modif', 'TrainingProgramme')
    TrainingProgrammeDisplay = apps.get_model('modif',
                                              'TrainingProgrammeDisplay')
    Groupe = apps.get_model('modif', 'Groupe')
    GroupDisplay = apps.get_model('modif', 'GroupDisplay')

    try:
        tp = TrainingProgramme.objects.get(abbrev = '3A')
        tp.abbrev = 'LP'
        tp.save()

        for g in Groupe.objects.filter(train_prog__abbrev = 'LP'):
            if g.surgroupe is None:
                g.nom = ''
                g.save()
        tpd = TrainingProgrammeDisplay(training_programme = tp,
                                       row = 1)
        tpd.save()

        tp = TrainingProgramme.objects.get(abbrev = '2A')
        tpd = TrainingProgrammeDisplay(training_programme = tp,
                                       row = 1)
        tpd.save()
        tp = TrainingProgramme.objects.get(abbrev = '1A')
        tpd = TrainingProgrammeDisplay(training_programme = tp,
                                       row = 0)
        tpd.save()
        gp = Groupe.objects.get(train_prog__abbrev = '1A',
                                surgroupe = None)
        gpd = GroupDisplay(group = gp,
                           button_txt = 'Groupes prem. an.')
        gpd.save()
        gp = Groupe.objects.get(train_prog__abbrev = '2A',
                                surgroupe = None)
        gpd = GroupDisplay(group = gp,
                           button_txt = 'Groupes deux. an.')
        gpd.save()
        gp = Groupe.objects.get(train_prog__abbrev = '2A',
                                nom = '1')
        gpd = GroupDisplay(group = gp,
                           button_height = 130)
        gpd.save()
        gp = Groupe.objects.get(train_prog__abbrev = '2A',
                                nom = '23')
        gpd = GroupDisplay(group = gp,
                           button_height = 65)
        gpd.save()
        gp = Groupe.objects.get(train_prog__abbrev = '2A',
                                nom = '2')
        gpd = GroupDisplay(group = gp,
                           button_height = 65)
        gpd.save()
        gp = Groupe.objects.get(train_prog__abbrev = '2A',
                                nom = '3')
        gpd = GroupDisplay(group = gp,
                           button_height = 65)
        gpd.save()
        gp = Groupe.objects.get(train_prog__abbrev = 'LP',
                                nom = '')
        gpd = GroupDisplay(group = gp,
                           button_height = 165)
        gpd.save()

        tp = TrainingProgramme.objects.get(abbrev = 'LP')

        gp = Groupe(nom = 'fLP1',
                    train_prog = tp,
                    nature = Groupe.TP,
                    surgroupe = Groupe.objects.get(nom = '',
                                                   train_prog = tp),
                    basic = True,
                    taille = 0)
        gp.save()
        gp = Groupe(nom = 'fLP2',
                    train_prog = tp,
                    nature = Groupe.TP,
                    surgroupe = Groupe.objects.get(nom = '',
                                                   train_prog = tp),
                    basic = True)
        gp.save()
        gp = Groupe.objects.get(nom = 'fLP1')
        gpd = GroupDisplay(group = gp,
                           button_height = 0,
                           button_txt = '')
        gpd.save()
        gp = Groupe.objects.get(nom = 'fLP2')
        gpd = GroupDisplay(group = gp,
                           button_height = 0,
                           button_txt = '')
        gpd.save()

    except:
        print "pas réussi à changer toutes les infos de la promo LP"


class Migration(migrations.Migration):

    dependencies = [
        ('modif', '0006_displays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduledisplay',
            name='color',
        ),
        migrations.AddField(
            model_name='moduledisplay',
            name='color_bg',
            field=models.CharField(default='red', max_length=20),
        ),
        migrations.AddField(
            model_name='moduledisplay',
            name='color_txt',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AlterField(
            model_name = 'groupdisplay',
            name = 'button_height',
            field = models.PositiveIntegerField(default = None, null = True),
        ),
        migrations.AlterField(
            model_name = 'groupdisplay',
            name = 'button_txt',
            field = models.CharField(default = None, max_length = 20,
                                     null = True),
        ),
        migrations.RunPython(move_LP_n_displays),
    ]
