# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modif', '0006_auto_20180604_1201'),
    ]

    operations = [
    ]
