# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 22:48
from __future__ import unicode_literals

from django.db import migrations

def add_buttxt(apps, schema_editor):
    GroupDisplay = apps.get_model('modif', 'GroupDisplay')
    try:
        gpd = GroupDisplay.objects.get(group__nom = "23")
        gpd.button_txt = u'2 & 3'
        gpd.save()
        gpd = GroupDisplay.objects.get(group__nom = "",
                                       group__train_prog__abbrev = 'LP')
        gpd.button_txt = u'LP'
        gpd.save()
    except:
        raise Exception('what about group 23?')

class Migration(migrations.Migration):

    dependencies = [
        ('modif', '0007_colors_change_3A'),
    ]

    operations = [
        migrations.RunPython(add_buttxt),
    ]
