# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modif', '0008_auto_20180604_1244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FakeUser',
        ),
        migrations.AlterField(
            model_name='coursmodification',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coutprof',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planifmodification',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operated_planif_modif', to=settings.AUTH_USER_MODEL),
        ),
    ]
