# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 18:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modif', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvoidBothSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('year', models.PositiveSmallIntegerField(default=None, null=True)),
                ('weight', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('promo', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.Groupe')),
                ('prof', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.Prof')),
                ('slot1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot1', to='modif.Creneau')),
                ('slot2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot2', to='modif.Creneau')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LimitNaturePerPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('year', models.PositiveSmallIntegerField(default=None, null=True)),
                ('weight', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nature', models.CharField(choices=[('CM', 'Cours magistral'), ('TD', 'Travaux Dirig\xe9s'), ('TP', 'Travaux Pratiques'), ('DS', 'Devoir surveill\xe9')], max_length=2, null=True)),
                ('limit', models.PositiveSmallIntegerField()),
                ('promo', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('period', models.CharField(choices=[('fd', 'Full day'), ('hd', 'Half day')], max_length=2)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.Module')),
                ('prof', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.Prof')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MinHalfDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('year', models.PositiveSmallIntegerField(default=None, null=True)),
                ('weight', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('join2courses', models.BooleanField(default=False, verbose_name='If 2 or 4 courses only, join it?')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.Module')),
                ('prof', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.Prof')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MinNonPreferedSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('year', models.PositiveSmallIntegerField(default=None, null=True)),
                ('weight', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('promo', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('prof', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.Prof')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReasonableDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('year', models.PositiveSmallIntegerField(default=None, null=True)),
                ('weight', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('promo', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.Groupe')),
                ('prof', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.Prof')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimultaneousCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('year', models.PositiveSmallIntegerField(default=None, null=True)),
                ('weight', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('course1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course1', to='modif.Cours')),
                ('course2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course2', to='modif.Cours')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stabilize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('year', models.PositiveSmallIntegerField(default=None, null=True)),
                ('weight', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('general', models.BooleanField(default=False, verbose_name='Stabiliser tout?')),
                ('promo', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('nature', models.CharField(choices=[('CM', 'Cours magistral'), ('TD', 'Travaux Dirig\xe9s'), ('TP', 'Travaux Pratiques'), ('DS', 'Devoir surveill\xe9')], default=None, max_length=2, null=True)),
                ('work_copy', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.Groupe')),
                ('module', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.Module')),
                ('prof', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.Prof')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
