# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modif', '0001_initial'),
        ('TTapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stabilize',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.Group'),
        ),
        migrations.AddField(
            model_name='stabilize',
            name='module',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.Module'),
        ),
        migrations.AddField(
            model_name='stabilize',
            name='train_prog',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modif.TrainingProgramme'),
        ),
    ]
