# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TTapp', '0002_add_train_prog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avoidbothslots',
            name='promo',
        ),
        migrations.RemoveField(
            model_name='limitnatureperperiod',
            name='promo',
        ),
        migrations.RemoveField(
            model_name='minnonpreferedslot',
            name='promo',
        ),
        migrations.RemoveField(
            model_name='reasonabledays',
            name='promo',
        ),
        migrations.RemoveField(
            model_name='stabilize',
            name='promo',
        ),
    ]
