# Generated by Django 2.1.4 on 2019-05-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTapp', '0010_customconstraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customconstraint',
            name='class_name',
            field=models.CharField(max_length=200),
        ),
    ]
