# Generated by Django 2.1.4 on 2019-06-03 20:46

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20190424_1054'),
        ('people', '0007_auto_20190311_1920'),
        ('TTapp', '0011_auto_20190527_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvoidBothTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('year', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('weight', models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('comment', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Contrainte active?')),
                ('time1', models.PositiveSmallIntegerField()),
                ('time2', models.PositiveSmallIntegerField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Group')),
                ('train_prog', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TrainingProgramme')),
                ('tutor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Tutor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LimitCourseTypeTimePerPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('year', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('weight', models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('comment', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Contrainte active?')),
                ('max_hours', models.PositiveSmallIntegerField()),
                ('period', models.CharField(choices=[('fd', 'Full day'), ('hd', 'Half day')], max_length=2)),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.CourseType')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department')),
                ('module', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Module')),
                ('train_prog', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TrainingProgramme')),
                ('tutors', models.ManyToManyField(blank=True, related_name='Course_type_limits', to='people.Tutor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LimitedStartTimeChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('year', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('weight', models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('comment', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Contrainte active?')),
                ('possible_start_times', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department')),
                ('group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Group')),
                ('module', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Module')),
                ('train_prog', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TrainingProgramme')),
                ('tutor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Tutor')),
                ('type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.CourseType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='avoidbothslots',
            name='department',
        ),
        migrations.RemoveField(
            model_name='avoidbothslots',
            name='group',
        ),
        migrations.RemoveField(
            model_name='avoidbothslots',
            name='slot1',
        ),
        migrations.RemoveField(
            model_name='avoidbothslots',
            name='slot2',
        ),
        migrations.RemoveField(
            model_name='avoidbothslots',
            name='train_prog',
        ),
        migrations.RemoveField(
            model_name='avoidbothslots',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='limitcoursetypeperperiod',
            name='department',
        ),
        migrations.RemoveField(
            model_name='limitcoursetypeperperiod',
            name='module',
        ),
        migrations.RemoveField(
            model_name='limitcoursetypeperperiod',
            name='train_prog',
        ),
        migrations.RemoveField(
            model_name='limitcoursetypeperperiod',
            name='tutors',
        ),
        migrations.RemoveField(
            model_name='limitcoursetypeperperiod',
            name='type',
        ),
        migrations.RemoveField(
            model_name='limitedslotchoices',
            name='department',
        ),
        migrations.RemoveField(
            model_name='limitedslotchoices',
            name='group',
        ),
        migrations.RemoveField(
            model_name='limitedslotchoices',
            name='module',
        ),
        migrations.RemoveField(
            model_name='limitedslotchoices',
            name='possible_slots',
        ),
        migrations.RemoveField(
            model_name='limitedslotchoices',
            name='train_prog',
        ),
        migrations.RemoveField(
            model_name='limitedslotchoices',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='limitedslotchoices',
            name='type',
        ),
        migrations.DeleteModel(
            name='AvoidBothSlots',
        ),
        migrations.DeleteModel(
            name='LimitCourseTypePerPeriod',
        ),
        migrations.DeleteModel(
            name='LimitedSlotChoices',
        ),
    ]
