# Generated by Django 2.1.15 on 2020-03-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_remove_room_basic'),
        ('TTapp', '0013_auto_20191028_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitcoursetypetimeperperiod',
            name='module',
        ),
        migrations.AddField(
            model_name='limitcoursetypetimeperperiod',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='Course_type_limits', to='base.Module'),
        ),
    ]
