# Generated by Django 3.0.5 on 2020-05-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TTapp', '0015_auto_20200414_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limitedroomchoices',
            old_name='type',
            new_name='course_type',
        ),
        migrations.RenameField(
            model_name='limitedstarttimechoices',
            old_name='type',
            new_name='course_type',
        ),
        migrations.RenameField(
            model_name='stabilize',
            old_name='type',
            new_name='course_type',
        ),
    ]
