# Generated by Django 3.0.5 on 2020-05-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_notificationspreferences'),
        ('TTapp', '0020_lowerboundbusydays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minnonpreferedtutorsslot',
            name='tutors',
            field=models.ManyToManyField(blank=True, related_name='min_non_prefered_tutors_slots_constraints', to='people.Tutor'),
        ),
    ]
