# Generated by Django 3.0.5 on 2020-05-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTapp', '0025_auto_20200520_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakaroundcoursetype',
            name='min_break_length',
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
