# Generated by Django 3.0.5 on 2020-06-18 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_moduletutorrepartition'),
        ('TTapp', '0027_stabilizationthroughweeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitgroupscoursetypetimeperperiod',
            name='course_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.CourseType'),
        ),
        migrations.AlterField(
            model_name='limitmodulescoursetypetimeperperiod',
            name='course_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.CourseType'),
        ),
        migrations.AlterField(
            model_name='limittutorscoursetypetimeperperiod',
            name='course_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.CourseType'),
        ),
    ]
