# Generated by Django 3.0.5 on 2020-07-23 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTapp', '0031_boundvisiohalfdays_limitgroupsphysicalpresence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundvisiohalfdays',
            name='nb_min',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)]),
        ),
    ]
