# Generated by Django 3.0.5 on 2020-08-06 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_courseadditional'),
        ('people', '0017_notificationspreferences'),
        ('TTapp', '0032_auto_20200723_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedstarttimechoices',
            name='course_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.CourseType'),
        ),
        migrations.AlterField(
            model_name='limitedstarttimechoices',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Group'),
        ),
        migrations.AlterField(
            model_name='limitedstarttimechoices',
            name='module',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Module'),
        ),
        migrations.AlterField(
            model_name='limitedstarttimechoices',
            name='tutor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Tutor'),
        ),
    ]
