# Generated by Django 3.0.5 on 2020-11-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_grouppreferredlinks'),
        ('TTapp', '0035_auto_20201005_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='novisio',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='no_visio', to='base.Module'),
        ),
        migrations.AddField(
            model_name='visioonly',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='visio_only', to='base.Module'),
        ),
    ]
