# Generated by Django 3.0.5 on 2021-01-02 14:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTapp', '0036_auto_20201104_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitedstarttimechoices',
            name='possible_week_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('m', 'monday'), ('tu', 'tuesday'), ('w', 'wednesday'), ('th', 'thursday'), ('f', 'friday'), ('sa', 'saturday'), ('su', 'sunday')], max_length=2), blank=True, null=True, size=None),
        ),
    ]
