# Generated by Django 3.0.5 on 2021-03-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_grouppreferredlinks'),
        ('TTapp', '0041_considerdepencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='considerdepencies',
            name='modules',
            field=models.ManyToManyField(blank=True, to='base.Module'),
        ),
    ]
