# Generated by Django 3.0.5 on 2021-03-29 14:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0027_auto_20210314_1603'),
        ('base', '0068_auto_20210314_0047'),
        ('TTapp', '0042_auto_20210301_2100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoCourseOnDay',
            new_name='NoGroupCourseOnDay',
        ),
        migrations.CreateModel(
            name='NoTutorCourseOnDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('year', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('weight', models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('comment', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Contrainte active?')),
                ('period', models.CharField(choices=[('fd', 'Full day'), ('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('weekday', models.CharField(choices=[('m', 'monday'), ('tu', 'tuesday'), ('w', 'wednesday'), ('th', 'thursday'), ('f', 'friday'), ('sa', 'saturday'), ('su', 'sunday')], max_length=2)),
                ('tutor_status', models.CharField(blank=True, choices=[('fs', 'Full staff'), ('ss', 'Supply staff'), ('bi', 'BIATOS')], max_length=2, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department')),
                ('train_progs', models.ManyToManyField(blank=True, to='base.TrainingProgramme')),
                ('tutors', models.ManyToManyField(blank=True, to='people.Tutor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
