# Generated by Django 3.1.7 on 2021-07-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_auto_20210710_2236'),
        ('TTapp', '0047_auto_20210510_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avoidbothtimes',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='boundphysicalpresencehalfdays',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='breakaroundcoursetype',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='considerdepencies',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='curfew',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='customconstraint',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='groupslunchbreak',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='limitedroomchoices',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='limitedstarttimechoices',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='limitgroupsphysicalpresence',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='limitgroupstimeperperiod',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='limitmodulestimeperperiod',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='limittutorstimeperperiod',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='lowerboundbusydays',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='mingroupshalfdays',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='minimizebusydays',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='minmoduleshalfdays',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='minnonpreferedtrainprogsslot',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='minnonpreferedtutorsslot',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='mintutorshalfdays',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='nogroupcourseonday',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='notutorcourseonday',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='novisio',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='respectboundperday',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='simultaneouscourses',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='stabilizationthroughweeks',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='stabilize',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='tutorslunchbreak',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
        migrations.AlterField(
            model_name='visioonly',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='base.Week'),
        ),
    ]
