# Generated by Django 3.0.14 on 2021-07-05 14:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_auto_20210629_1405'),
        ('TTapp', '0049_auto_20210705_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precedence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('comment', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('modified_at', models.DateField(auto_now=True)),
                ('successive', models.BooleanField(default=False, verbose_name='Successives?')),
                ('day_gap', models.PositiveSmallIntegerField(default=0, verbose_name='Minimal day gap between courses')),
                ('course1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='base.Course')),
                ('course2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='base.Course')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department')),
                ('train_progs', models.ManyToManyField(blank=True, to='base.TrainingProgramme')),
                ('weeks', models.ManyToManyField(blank=True, to='base.Week')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
