# Generated by Django 3.1.7 on 2021-09-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTapp', '0050_auto_20210720_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignallcourses',
            name='pre_assigned_only',
            field=models.BooleanField(default=False, verbose_name='Pre-assigned courses only'),
        ),
    ]
