# Generated by Django 3.1.7 on 2021-10-07 10:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_auto_20210910_0753'),
        ('people', '0030_auto_20210618_1420'),
        ('TTapp', '0052_auto_20210928_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitUndesiredSlotsPerWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('comment', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('modified_at', models.DateField(auto_now=True)),
                ('slot_start_time', models.PositiveSmallIntegerField()),
                ('slot_end_time', models.PositiveSmallIntegerField()),
                ('max_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(7)])),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.department')),
                ('train_progs', models.ManyToManyField(blank=True, to='base.TrainingProgramme')),
                ('tutors', models.ManyToManyField(blank=True, to='people.Tutor')),
                ('weeks', models.ManyToManyField(blank=True, to='base.Week')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
