# Generated by Django 3.1.7 on 2021-12-17 08:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTapp', '0053_limitundesiredslotsperweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedstarttimechoices',
            name='possible_start_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=None),
        ),
    ]
