# Generated by Django 3.1.7 on 2022-01-07 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_auto_20211206_1200'),
        ('TTapp', '0055_limitsimultaneouscoursesnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitsimultaneouscoursesnumber',
            name='courses',
        ),
        migrations.AddField(
            model_name='limitsimultaneouscoursesnumber',
            name='course_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.coursetype'),
        ),
        migrations.AddField(
            model_name='limitsimultaneouscoursesnumber',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='limit_simultaneous', to='base.Module'),
        ),
    ]
