# Generated by Django 3.0.14 on 2022-02-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_roomponderation_basic_rooms'),
        ('TTapp', '0057_considerroomsorts_limitgroupmoves_limitroomchoices_limittutormoves_locateallcourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedroomchoices',
            name='possible_rooms',
            field=models.ManyToManyField(to='base.Room'),
        ),
        migrations.DeleteModel(
            name='LimitRoomChoices',
        ),
    ]
