# Generated by Django 3.0.14 on 2022-03-15 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_roomponderation_basic_rooms'),
        ('people', '0032_tutorpreference'),
        ('TTapp', '0059_auto_20220315_2128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RespectBoundPerDay',
            new_name='RespectMaxHoursPerDay',
        ),
        migrations.AlterModelOptions(
            name='respectmaxhoursperday',
            options={'verbose_name_plural': 'Respect max hours per day'},
        ),
    ]
