# Generated by Django 3.0.14 on 2022-11-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTapp', '0067_notaloneforthesecousetypes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notaloneforthesecousetypes',
            options={'verbose_name': 'Not alone for these course types', 'verbose_name_plural': 'Not alone for these course types'},
        ),
        migrations.RenameField(
            model_name='groupslunchbreak',
            old_name='end_time',
            new_name='end_lunch_time',
        ),
        migrations.RenameField(
            model_name='groupslunchbreak',
            old_name='start_time',
            new_name='start_lunch_time',
        ),
        migrations.RenameField(
            model_name='tutorslunchbreak',
            old_name='end_time',
            new_name='end_lunch_time',
        ),
        migrations.RenameField(
            model_name='tutorslunchbreak',
            old_name='start_time',
            new_name='start_lunch_time',
        ),
        migrations.RenameField(
            model_name='limitcoursetypetimeperperiod',
            old_name='period',
            new_name='fhd_period',
        ),
        migrations.RenameField(
            model_name='limitgroupstimeperperiod',
            old_name='period',
            new_name='fhd_period',
        ),
        migrations.RenameField(
            model_name='limitmodulestimeperperiod',
            old_name='period',
            new_name='fhd_period',
        ),
        migrations.RenameField(
            model_name='limittutorstimeperperiod',
            old_name='period',
            new_name='fhd_period',
        ),
        migrations.RenameField(
            model_name='nogroupcourseonday',
            old_name='period',
            new_name='fampm_period',
        ),
        migrations.RenameField(
            model_name='notutorcourseonday',
            old_name='period',
            new_name='fampm_period',
        ),
    ]
