# Generated by Django 3.0.14 on 2022-12-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0091_auto_20221124_2149'),
        ('TTapp', '0070_nosimultaneousroomcourses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoSimultaneousRoomCourses',
            new_name='LimitSimultaneousRoomCourses',
        ),
    ]
