# Generated by Django 3.0.14 on 2022-12-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTapp', '0071_auto_20221214_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitsimultaneousroomcourses',
            name='max_simultaneous_courses',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='max simultaneous courses'),
        ),
    ]
