# Generated by Django 2.1.3 on 2019-07-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateConfig',
        ),
    ]
