# Generated by Django 2.1.3 on 2019-04-23 21:28

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

def move_displays(apps, schema_editor):
    OldBreakingNews = apps.get_model('base', 'BreakingNews')
    NewBreakingNews = apps.get_model('displayweb', 'BreakingNews')
    OldGroupDisplay = apps.get_model('base', 'GroupDisplay')
    NewGroupDisplay = apps.get_model('displayweb', 'GroupDisplay')
    OldModuleDisplay = apps.get_model('base', 'ModuleDisplay')
    NewModuleDisplay = apps.get_model('displayweb', 'ModuleDisplay')
    OldTrainingProgrammeDisplay = apps.get_model('base', 'TrainingProgrammeDisplay')
    NewTrainingProgrammeDisplay = apps.get_model('displayweb', 'TrainingProgrammeDisplay')
    
    Department = apps.get_model('base', 'Department')
    Group = apps.get_model('base', 'Group')
    Module = apps.get_model('base', 'Module')
    TrainingProgramme = apps.get_model('base', 'TrainingProgramme')

    for bk in OldBreakingNews.objects.all():
        NewBreakingNews.objects.create(
            week=bk.week,
            year=bk.year,
            x_beg=bk.x_beg,
            x_end=bk.x_end,
            y=bk.y,
            txt=bk.txt,
            is_linkedk=bk.is_linked,
            fill_color=bk.fill_color,
            strk_color=bk.strk_color,
            department=bk.department
        )

    for gd in OldGroupDisplay.objects.all():
        NewGroupDisplay.objects.create(
            button_height=gd.button_height,
            button_txt=gd.button_txt,
            group=gd.group
        )

    for md in OldModuleDisplay.objects.all():
        NewModuleDisplay.objects.create(
            color_bg=md.color_bg,
            color_txt=md.color_txt,
            module=md.module
        )

    for td in OldTrainingProgrammeDisplay.objects.all():
        NewTrainingProgrammeDisplay.objects.create(
            row=td.row,
            short_name=td.short_name,
            training_programme=td.training_programme
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0031_auto_20190117_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakingNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(53)])),
                ('year', models.PositiveSmallIntegerField()),
                ('x_beg', models.FloatField(blank=True, default=2.0)),
                ('x_end', models.FloatField(blank=True, default=3.0)),
                ('y', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('txt', models.CharField(max_length=200)),
                ('is_linked', models.URLField(blank=True, default=None, null=True)),
                ('fill_color', colorfield.fields.ColorField(default='#228B22', max_length=18)),
                ('strk_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departmenttmp', to='base.Department')),
            ],
        ),
        migrations.CreateModel(
            name='GroupDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_height', models.PositiveIntegerField(default=None, null=True)),
                ('button_txt', models.CharField(default=None, max_length=20, null=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='displaytmp', to='base.Group')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_bg', models.CharField(default='red', max_length=20)),
                ('color_txt', models.CharField(default='black', max_length=20)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='displaytmp', to='base.Module')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgrammeDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveSmallIntegerField()),
                ('short_name', models.CharField(default='', max_length=20)),
                ('training_programme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='displaytmp', to='base.TrainingProgramme')),
            ],
        ),
        migrations.RunPython(move_displays),
    ]
