# Generated by Django 2.1.3 on 2019-04-24 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('displayweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakingnews',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department'),
        ),
        migrations.AlterField(
            model_name='groupdisplay',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='base.Group'),
        ),
        migrations.AlterField(
            model_name='moduledisplay',
            name='module',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='base.Module'),
        ),
        migrations.AlterField(
            model_name='trainingprogrammedisplay',
            name='training_programme',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='base.TrainingProgramme'),
        ),
    ]
