# Generated by Django 2.1.4 on 2019-10-28 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20190926_1259'),
        ('displayweb', '0002_auto_20190424_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_bg', models.CharField(default='red', max_length=20)),
                ('color_txt', models.CharField(default='black', max_length=20)),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='people.Tutor')),
            ],
        ),
    ]
