# Generated by Django 3.0.5 on 2020-05-15 18:18

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displayweb', '0003_tutordisplay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledisplay',
            name='color_bg',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='moduledisplay',
            name='color_txt',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AlterField(
            model_name='tutordisplay',
            name='color_bg',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='tutordisplay',
            name='color_txt',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
