# Generated by Django 3.1.7 on 2021-08-31 13:06

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displayweb', '0004_auto_20200515_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledisplay',
            name='color_bg',
            field=colorfield.fields.ColorField(default='#D3D3D3', max_length=18),
        ),
    ]
