from rest_framework import routers
from api import views

router = routers.SimpleRouter()

router.register(r'base/users', views.UsersViewSet)
router.register(r'base/userdepartmentsettings', views.UserDepartmentSettingsViewSet)
router.register(r'base/tutors', views.TutorsViewSet)
router.register(r'base/supplystaff', views.SupplyStaffsViewSet)
router.register(r'base/students', views.StudentsViewSet)
#router.register(r'base/preferences', views.PreferencesViewSet)
#router.register(r'base/studentspreferences', views.StudentPreferencesViewSet)
#router.register(r'base/groupspreferences', views.GroupPreferencesViewSet)

router.register(r'base/departments', views.DepartmentViewSet)
router.register(r'base/trainingprograms', views.TrainingProgramsViewSet)
router.register(r'base/grouptypes', views.GroupTypesViewSet)
router.register(r'base/grouptypes', views.GroupsViewSet)
router.register(r'base/days', views.DaysViewSet)
router.register(r'base/slots', views.SlotsViewSet)
router.register(r'base/holidays', views.HolidaysViewSet)
router.register(r'base/traininghalfdays', views.TrainingHalfDaysViewSet)
router.register(r'base/periods', views.PeriodsViewSet)
router.register(r'base/timesettings', views.TimeGeneralSettingsViewSet)
router.register(r'base/roomtypes', views.RoomTypesViewSet)
router.register(r'base/roomgroups', views.RoomGroupsViewSet)
router.register(r'base/rooms', views.RoomGroupsViewSet)
router.register(r'base/roomsorts', views.RoomSortsViewSet)
router.register(r'base/modules', views.ModulesViewSet)
router.register(r'base/coursetypes', views.CourseTypesViewSet)
router.register(r'base/courses', views.CoursesViewSet)
router.register(r'base/scheduledcourses', views.ScheduledCoursesViewSet)

router.register(r'people/userspreferences', views.UsersPreferencesViewSet)
router.register(r'people/coursepreferences', views.CoursePreferencesViewSet)
router.register(r'people/roompreferences', views.RoomPreferencesViewSet)
router.register(r'people/edtversions', views.EdtVersionsViewSet)
router.register(r'people/coursemodifications', views.CourseModificationsViewSet)
router.register(r'people/planningmodifications', views.PlanningModificationsViewSet)
router.register(r'people/tutorcosts', views.TutorCostsViewSet)
router.register(r'people/groupcosts', views.GroupCostsViewSet)
router.register(r'people/groupfreehalfdays', views.GroupFreeHalfDaysViewSet)
router.register(r'people/dependencies', views.DependenciesViewSet)
router.register(r'people/coursesstarttimeconstraints', views.CourseStartTimeConstraintsViewSet)
router.register(r'people/regens', views.RegensViewSet)

router.register(r'quote/quotetypes', views.QuoteTypesViewSet)
router.register(r'quote/quotes', views.QuotesViewSet)

router.register(r'displayweb/breakingnews', views.BreakingNewsViewSet)
router.register(r'displayweb/moduledisplays', views.ModuleDisplaysViewSet)
router.register(r'displayweb/trainingprogrammedisplays', views.TrainingProgrammeDisplaysViewSet)
router.register(r'displayweb/groupdisplays', views.GroupDisplaysViewSet)

urlpatterns = router.urls